name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      
      - name: Install Doxybook
        run: pip install doxybook
        
      - name: Install Sphinx
        run: sudo apt-get install python3-sphinx
      
      - name: Install Breathe
        run: pip install breathe
        
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        shell: bash

      - name: Generate Doxygen Documentation
        run: doxygen doc/doxygen/Doxyfile
        shell: bash

      - name: Create .nojekyll (ensures pages with underscores work on gh pages)
        run: touch doc/doxygen/html/.nojekyll
        shell: bash
      
      - name: Generate Markdown
        run: doxybook -i doc/doxygen/xml -o docs/api -t vuepress
        shell: bash
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc/doxygen/html
